import type { Hackathon } from "@/lib/types"

const teamJudges = [
  { name: "Dev Dharrshan", title: "Backend Lead", organization: "KEC, Erode Tamilnadu", image_url: "/team/dev-dharrshan.jpg" },
  { name: "Divyadharshini", title: "Frontend Lead", organization: "KEC, Erode Tamilnadu", image_url: "/team/divya-dharshini.jpg" },
  { name: "Anusree", title: "AI Specialist", organization: "KEC, Erode Tamilnadu", image_url: "/team/anusree.jpg" },
  { name: "Divakar", title: "Database Lead", organization: "KEC, Erode Tamilnadu", image_url: "/team/divakar.jpg" },
  { name: "Hemapriya", title: "UI/UX Lead", organization: "KEC, Erode Tamilnadu", image_url: "/team/hemapriya.jpg" },
  { name: "Bharani", title: "Cloud Lead", organization: "KEC, Erode Tamilnadu", image_url: "/team/bharani.jpg" },
]

const commonRules = [
  "Teams can have 2-6 members",
  "All project work must be completed during the event window",
  "Teams must submit a working demo, source code, and presentation",
  "Projects will be judged on innovation, implementation, usability, and impact",
  "Participants must follow the HackConnect code of conduct",
]

const schedule = [
  { time: "Day 1, 9:00 AM", activity: "Registration and team check-in" },
  { time: "Day 1, 10:00 AM", activity: "Opening ceremony and theme briefing" },
  { time: "Day 1, 11:00 AM", activity: "Hacking begins" },
  { time: "Day 1, 2:00 PM", activity: "Technical workshop" },
  { time: "Day 2, 10:00 AM", activity: "Progress review" },
  { time: "Day 2, 3:00 PM", activity: "Final submissions" },
  { time: "Day 2, 5:00 PM", activity: "Presentations and awards" },
]

const faq = [
  { question: "Where is the event conducted?", answer: "All listed HackConnect events are hosted at KEC, Erode Tamilnadu." },
  { question: "Can beginners participate?", answer: "Yes. Teams are encouraged to include members with different skill levels." },
  { question: "Can I join without a team?", answer: "Yes. You can join through the Find Your Team page and connect with existing teams." },
]

export const mockHackathons: Hackathon[] = [
  {
    id: "1",
    title: "AI Innovation Challenge",
    description: "Build useful AI tools for campus, healthcare, learning, and productivity using modern machine learning workflows.",
    image_url: "/ai-hackathon.png",
    start_date: "2026-07-10",
    end_date: "2026-07-11",
    location: "KEC, Erode Tamilnadu",
    type: "in-person",
    format: "competitive",
    themes: ["Artificial Intelligence", "Machine Learning", "Productivity"],
    max_participants: 300,
    current_participants: 126,
    status: "upcoming",
    prize_amount: 25000,
    skill_level: "intermediate",
    eligibility: "Open to KEC students and student developer teams",
    rules: commonRules,
    schedule,
    judges: teamJudges.slice(0, 3),
    faq,
    resources: [{ title: "Starter datasets", url: "https://www.kaggle.com/datasets", type: "dataset" }],
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "2",
    title: "Web3 Builders Hackathon",
    description: "Create secure blockchain prototypes for certificates, voting, payments, or transparent record keeping.",
    image_url: "/blockchain-hackathon.png",
    start_date: "2026-07-17",
    end_date: "2026-07-18",
    location: "KEC, Erode Tamilnadu",
    type: "in-person",
    format: "competitive",
    themes: ["Blockchain", "Smart Contracts", "Web3"],
    max_participants: 240,
    current_participants: 98,
    status: "upcoming",
    prize_amount: 20000,
    skill_level: "advanced",
    eligibility: "Open to student teams",
    rules: commonRules,
    schedule,
    judges: [teamJudges[3], teamJudges[4], teamJudges[5]],
    faq,
    resources: [{ title: "Solidity documentation", url: "https://docs.soliditylang.org/", type: "documentation" }],
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "3",
    title: "Green Tech Sprint",
    description: "Design technology that supports sustainability, energy tracking, recycling, smart farming, or water conservation.",
    image_url: "/sustainability-dashboard.png",
    start_date: "2026-07-24",
    end_date: "2026-07-25",
    location: "KEC, Erode Tamilnadu",
    type: "in-person",
    format: "community",
    themes: ["Sustainability", "IoT", "Climate Tech"],
    max_participants: 280,
    current_participants: 143,
    status: "upcoming",
    prize_amount: 18000,
    skill_level: "all-levels",
    eligibility: "Open to all branches",
    rules: commonRules,
    schedule,
    judges: [teamJudges[1], teamJudges[2], teamJudges[4]],
    faq,
    resources: [{ title: "Sustainable development goals", url: "https://sdgs.un.org/goals", type: "reference" }],
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "4",
    title: "Mobile App Innovation",
    description: "Build mobile-first apps for student services, safety, learning, events, or local community needs.",
    image_url: "/hackathon-mobile.svg",
    start_date: "2026-07-31",
    end_date: "2026-08-01",
    location: "KEC, Erode Tamilnadu",
    type: "in-person",
    format: "competitive",
    themes: ["Mobile Development", "UI/UX", "App Innovation"],
    max_participants: 220,
    current_participants: 87,
    status: "upcoming",
    prize_amount: 15000,
    skill_level: "beginner",
    eligibility: "Open to student teams",
    rules: commonRules,
    schedule,
    judges: [teamJudges[0], teamJudges[1], teamJudges[4]],
    faq,
    resources: [{ title: "React Native guide", url: "https://reactnative.dev/docs/getting-started", type: "tutorial" }],
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "5",
    title: "Cyber Security CodeFest",
    description: "Create practical security tools, awareness platforms, safe authentication flows, or vulnerability dashboards.",
    image_url: "/hackathon-security.svg",
    start_date: "2026-08-07",
    end_date: "2026-08-08",
    location: "KEC, Erode Tamilnadu",
    type: "in-person",
    format: "learning",
    themes: ["Cybersecurity", "Authentication", "Secure Coding"],
    max_participants: 200,
    current_participants: 76,
    status: "upcoming",
    prize_amount: 17000,
    skill_level: "intermediate",
    eligibility: "Open to student developers",
    rules: commonRules,
    schedule,
    judges: [teamJudges[0], teamJudges[3], teamJudges[5]],
    faq,
    resources: [{ title: "OWASP Top 10", url: "https://owasp.org/www-project-top-ten/", type: "reference" }],
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "6",
    title: "IoT Smart Campus Hack",
    description: "Prototype connected devices and dashboards for smart classrooms, parking, energy, attendance, or campus safety.",
    image_url: "/hackathon-iot.svg",
    start_date: "2026-08-14",
    end_date: "2026-08-15",
    location: "KEC, Erode Tamilnadu",
    type: "in-person",
    format: "community",
    themes: ["IoT", "Embedded Systems", "Smart Campus"],
    max_participants: 180,
    current_participants: 64,
    status: "upcoming",
    prize_amount: 16000,
    skill_level: "all-levels",
    eligibility: "Open to hardware and software teams",
    rules: commonRules,
    schedule,
    judges: [teamJudges[2], teamJudges[3], teamJudges[5]],
    faq,
    resources: [{ title: "Arduino documentation", url: "https://docs.arduino.cc/", type: "documentation" }],
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "7",
    title: "Game Dev Jam",
    description: "Design a playable browser, mobile, or desktop game with polished mechanics and a clear theme.",
    image_url: "/hackathon-game.svg",
    start_date: "2026-08-21",
    end_date: "2026-08-22",
    location: "KEC, Erode Tamilnadu",
    type: "in-person",
    format: "competitive",
    themes: ["Game Development", "Creative Coding", "Interactive Design"],
    max_participants: 160,
    current_participants: 59,
    status: "upcoming",
    prize_amount: 14000,
    skill_level: "beginner",
    eligibility: "Open to creative student teams",
    rules: commonRules,
    schedule,
    judges: [teamJudges[1], teamJudges[4], teamJudges[5]],
    faq,
    resources: [{ title: "Phaser documentation", url: "https://docs.phaser.io/", type: "documentation" }],
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
  },
]
