import type { Hackathon } from "@/lib/types"

const commonRules = [
  "Teams can have 1-5 members",
  "All work must be created during the hackathon window",
  "A working demo or prototype is required",
  "Submissions must include a short project explanation",
]

const commonFaq = [
  {
    question: "Can beginners participate?",
    answer: "Yes. Each event includes beginner-friendly workshops and mentor support.",
  },
  {
    question: "Do I need a team before registering?",
    answer: "No. You can register solo and form a team during the event.",
  },
]

export const mockHackathons: Hackathon[] = [
  {
    id: "devpost-1",
    title: "2026 Global Challenge Hackathon",
    description:
      "Build practical AI solutions for education, healthcare, automation, and accessibility with mentor support throughout the event.",
    image_url: "/ai-hackathon-event.png",
    start_date: "2026-03-15",
    end_date: "2026-03-17",
    location: "Virtual",
    type: "online",
    format: "competitive",
    themes: ["Artificial Intelligence", "Machine Learning", "Computer Vision", "NLP"],
    max_participants: 1000,
    current_participants: 650,
    status: "upcoming",
    prize_amount: 50000,
    skill_level: "intermediate",
    eligibility: "Open to all developers 18+",
    rules: commonRules,
    schedule: [
      { time: "Mar 15, 2026, 9:00 AM", activity: "Opening Ceremony" },
      { time: "Mar 15, 2026, 10:00 AM", activity: "Hacking Begins" },
      { time: "Mar 17, 2026, 5:00 PM", activity: "Submission Deadline" },
      { time: "Mar 17, 2026, 7:00 PM", activity: "Awards Ceremony" },
    ],
    judges: [{ name: "Dev Dharrshan", title: "AI Research Director", organization: "HackConnect", image_url: "/team/dev-dharrshan.jpg" }],
    sponsors: [{ name: "HackConnect", tier: "Platinum", logo_url: "/hackconnect-logo.svg" }],
    faq: commonFaq,
    resources: [{ title: "AI Starter Guide", url: "https://example.com/ai-guide", type: "tutorial" }],
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "devpost-2",
    title: "Blockchain Developer Challenge",
    description:
      "Create secure Web3 apps, smart contracts, wallets, DeFi tools, and transparent blockchain workflows.",
    image_url: "/blockchain-hackathon.png",
    start_date: "2024-02-10",
    end_date: "2024-02-12",
    location: "IIT Delhi, New Delhi",
    type: "hybrid",
    format: "competitive",
    themes: ["Blockchain", "DeFi", "Web3", "Smart Contracts"],
    max_participants: 500,
    current_participants: 320,
    status: "upcoming",
    prize_amount: 30000,
    skill_level: "advanced",
    eligibility: "Developers with blockchain interest",
    rules: commonRules,
    schedule: [
      { time: "Feb 10, 8:00 AM", activity: "Registration" },
      { time: "Feb 10, 10:00 AM", activity: "Hacking Begins" },
      { time: "Feb 12, 4:00 PM", activity: "Submission Deadline" },
      { time: "Feb 12, 6:00 PM", activity: "Presentations" },
    ],
    judges: [{ name: "Divya Dharshini", title: "Founder", organization: "HackConnect", image_url: "/team/divya-dharshini.jpg" }],
    sponsors: [{ name: "Web3 Labs", tier: "Gold", logo_url: "/placeholder-logo.svg" }],
    faq: commonFaq,
    resources: [{ title: "Smart Contract Toolkit", url: "https://example.com/smart-contracts", type: "tutorial" }],
    created_at: "2024-01-20T00:00:00Z",
    updated_at: "2024-01-20T00:00:00Z",
  },
  {
    id: "devpost-3",
    title: "Sustainable Technology Hackathon",
    description:
      "Design climate tech, clean-energy dashboards, smart recycling tools, and products that reduce environmental impact.",
    image_url: "/sustainability-dashboard.png",
    start_date: "2024-04-20",
    end_date: "2024-04-22",
    location: "IIT Bhubaneswar, Odisha",
    type: "in-person",
    format: "competitive",
    themes: ["Sustainability", "Clean Energy", "Climate Tech", "Green Technology"],
    max_participants: 400,
    current_participants: 180,
    status: "upcoming",
    prize_amount: 25000,
    skill_level: "all-levels",
    eligibility: "Open to all with passion for sustainability",
    rules: commonRules,
    schedule: [
      { time: "Apr 20, 9:00 AM", activity: "Registration" },
      { time: "Apr 20, 11:00 AM", activity: "Hacking Begins" },
      { time: "Apr 22, 3:00 PM", activity: "Submission Deadline" },
      { time: "Apr 22, 5:00 PM", activity: "Awards" },
    ],
    judges: [{ name: "Dhivakar", title: "Data Manager", organization: "HackConnect", image_url: "/team/divakar.jpg" }],
    sponsors: [{ name: "Eco Ventures", tier: "Gold", logo_url: "/placeholder-logo.svg" }],
    faq: commonFaq,
    resources: [{ title: "Environmental Data APIs", url: "https://example.com/env-data", type: "api" }],
    created_at: "2024-02-01T00:00:00Z",
    updated_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "devpost-4",
    title: "Full Stack Sprint",
    description: "Ship a polished web app with authentication, dashboard flows, APIs, and deployment in one focused sprint.",
    image_url: "/coding-hackathon.png",
    start_date: "2024-05-03",
    end_date: "2024-05-05",
    location: "Virtual",
    type: "online",
    format: "learning",
    themes: ["Web Apps", "APIs", "Product Design", "Deployment"],
    max_participants: 600,
    current_participants: 410,
    status: "upcoming",
    prize_amount: 18000,
    skill_level: "beginner",
    eligibility: "Students and early builders",
    rules: commonRules,
    schedule: [{ time: "May 03, 10:00 AM", activity: "Kickoff" }, { time: "May 05, 6:00 PM", activity: "Demo Day" }],
    judges: [{ name: "Hemapriya", title: "UI/UX Designer", organization: "HackConnect", image_url: "/team/hemapriya.jpg" }],
    sponsors: [{ name: "Code Studio", tier: "Silver", logo_url: "/placeholder-logo.svg" }],
    faq: commonFaq,
    resources: [{ title: "Next.js Deployment Notes", url: "https://example.com/web", type: "guide" }],
    created_at: "2024-02-10T00:00:00Z",
    updated_at: "2024-02-10T00:00:00Z",
  },
  {
    id: "devpost-5",
    title: "Cyber Shield Hack",
    description: "Build security tools, threat dashboards, awareness games, password managers, and safe browsing solutions.",
    image_url: "/docker-containers-guide.png",
    start_date: "2024-06-07",
    end_date: "2024-06-09",
    location: "IIT Bombay, Mumbai",
    type: "hybrid",
    format: "competitive",
    themes: ["Cybersecurity", "Privacy", "DevSecOps", "Identity"],
    max_participants: 450,
    current_participants: 275,
    status: "upcoming",
    prize_amount: 22000,
    skill_level: "intermediate",
    eligibility: "Open to security-minded builders",
    rules: commonRules,
    schedule: [{ time: "Jun 07, 9:00 AM", activity: "Security Briefing" }, { time: "Jun 09, 5:00 PM", activity: "Judging" }],
    judges: [{ name: "Bharani", title: "Cloud Architect", organization: "HackConnect", image_url: "/team/bharani.jpg" }],
    sponsors: [{ name: "SecureStack", tier: "Gold", logo_url: "/placeholder-logo.svg" }],
    faq: commonFaq,
    resources: [{ title: "Secure Coding Checklist", url: "https://example.com/security", type: "checklist" }],
    created_at: "2024-02-12T00:00:00Z",
    updated_at: "2024-02-12T00:00:00Z",
  },
  {
    id: "devpost-6",
    title: "Mobile Innovation Jam",
    description: "Prototype helpful mobile experiences for campus life, health, productivity, fintech, and social impact.",
    image_url: "/ai-task-manager.png",
    start_date: "2024-07-12",
    end_date: "2024-07-14",
    location: "Virtual",
    type: "online",
    format: "community",
    themes: ["Mobile", "React Native", "UX", "Productivity"],
    max_participants: 550,
    current_participants: 340,
    status: "upcoming",
    prize_amount: 16000,
    skill_level: "all-levels",
    eligibility: "Open to designers and developers",
    rules: commonRules,
    schedule: [{ time: "Jul 12, 6:00 PM", activity: "Idea Pitch" }, { time: "Jul 14, 4:00 PM", activity: "Final Demos" }],
    judges: [{ name: "Anusree", title: "AI Specialist", organization: "HackConnect", image_url: "/team/anusree.jpg" }],
    sponsors: [{ name: "AppWorks", tier: "Silver", logo_url: "/placeholder-logo.svg" }],
    faq: commonFaq,
    resources: [{ title: "Mobile UX Kit", url: "https://example.com/mobile", type: "kit" }],
    created_at: "2024-02-14T00:00:00Z",
    updated_at: "2024-02-14T00:00:00Z",
  },
  {
    id: "devpost-7",
    title: "Data Science Challenge",
    description: "Use datasets, dashboards, predictive models, and storytelling to solve business and public-sector problems.",
    image_url: "/ai-development-tools.png",
    start_date: "2024-08-09",
    end_date: "2024-08-11",
    location: "NIT Trichy, Tamil Nadu",
    type: "in-person",
    format: "learning",
    themes: ["Data Science", "Analytics", "Visualization", "Forecasting"],
    max_participants: 350,
    current_participants: 220,
    status: "upcoming",
    prize_amount: 20000,
    skill_level: "intermediate",
    eligibility: "Open to data enthusiasts",
    rules: commonRules,
    schedule: [{ time: "Aug 09, 10:00 AM", activity: "Dataset Release" }, { time: "Aug 11, 3:00 PM", activity: "Insight Presentations" }],
    judges: [{ name: "Divya Dharshini", title: "Founder", organization: "HackConnect", image_url: "/team/divya-dharshini.jpg" }],
    sponsors: [{ name: "Insight Labs", tier: "Gold", logo_url: "/placeholder-logo.svg" }],
    faq: commonFaq,
    resources: [{ title: "Data Storytelling Guide", url: "https://example.com/data", type: "guide" }],
    created_at: "2024-02-16T00:00:00Z",
    updated_at: "2024-02-16T00:00:00Z",
  },
  {
    id: "devpost-8",
    title: "Open Source Weekend",
    description: "Improve developer tools, documentation, starter kits, libraries, and community-first open source projects.",
    image_url: "/react-code-patterns.png",
    start_date: "2024-09-21",
    end_date: "2024-09-22",
    location: "Virtual",
    type: "online",
    format: "community",
    themes: ["Open Source", "Developer Tools", "Documentation", "Libraries"],
    max_participants: 700,
    current_participants: 515,
    status: "upcoming",
    prize_amount: 12000,
    skill_level: "beginner",
    eligibility: "Open to contributors of all levels",
    rules: commonRules,
    schedule: [{ time: "Sep 21, 9:00 AM", activity: "Repo Onboarding" }, { time: "Sep 22, 7:00 PM", activity: "Maintainer Reviews" }],
    judges: [{ name: "Dev Dharrshan", title: "Co Founder", organization: "HackConnect", image_url: "/team/dev-dharrshan.jpg" }],
    sponsors: [{ name: "OpenDev", tier: "Silver", logo_url: "/placeholder-logo.svg" }],
    faq: commonFaq,
    resources: [{ title: "Contribution Guide", url: "https://example.com/oss", type: "guide" }],
    created_at: "2024-02-18T00:00:00Z",
    updated_at: "2024-02-18T00:00:00Z",
  },
  {
    id: "devpost-9",
    title: "Startup Prototype Arena",
    description: "Turn a raw startup idea into a clickable, testable product prototype with pitch support and mentor reviews.",
    image_url: "/system-design-instagram.png",
    start_date: "2024-10-18",
    end_date: "2024-10-20",
    location: "Anna University, Chennai",
    type: "hybrid",
    format: "corporate",
    themes: ["Startup", "MVP", "Pitching", "Product Strategy"],
    max_participants: 300,
    current_participants: 190,
    status: "upcoming",
    prize_amount: 35000,
    skill_level: "all-levels",
    eligibility: "Open to student founders and makers",
    rules: commonRules,
    schedule: [{ time: "Oct 18, 9:30 AM", activity: "Founder Briefing" }, { time: "Oct 20, 6:00 PM", activity: "Pitch Finals" }],
    judges: [{ name: "Divya Dharshini", title: "Founder", organization: "HackConnect", image_url: "/team/divya-dharshini.jpg" }],
    sponsors: [{ name: "LaunchPad", tier: "Platinum", logo_url: "/placeholder-logo.svg" }],
    faq: commonFaq,
    resources: [{ title: "Pitch Deck Template", url: "https://example.com/startup", type: "template" }],
    created_at: "2024-02-20T00:00:00Z",
    updated_at: "2024-02-20T00:00:00Z",
  },
]
