// Mock data for users API with ranking metrics
export const mockUsers = [
  {
    id: "dev-dharrshan",
    name: "Dev Dharrshan",
    email: "devdharrshan@hackconnect.dev",
    title: "Backend Lead",
    bio: "Backend developer focused on scalable APIs and system architecture.",
    skills: ["Node.js", "TypeScript", "PostgreSQL", "API Design"],
    avatar_url: "/team/dev-dharrshan.jpg",
    hackathons_won: 8,
    hackathons_participated: 15,
    total_projects: 12,
    skill_endorsements: 45,
    years_experience: 5,
    github_contributions: 1250,
    ranking_score: 0,
    rank: 0,
    created_at: "2026-06-01T10:00:00Z",
    updated_at: "2026-06-01T10:00:00Z",
  },
  {
    id: "divyadharshini",
    name: "Divyadharshini",
    email: "divyadharshini@hackconnect.dev",
    title: "Frontend Lead",
    bio: "Frontend developer focused on responsive product interfaces.",
    skills: ["React", "Next.js", "Tailwind CSS", "UI Engineering"],
    avatar_url: "/team/divya-dharshini.jpg",
    hackathons_won: 12,
    hackathons_participated: 18,
    total_projects: 25,
    skill_endorsements: 78,
    years_experience: 4,
    github_contributions: 890,
    ranking_score: 0,
    rank: 0,
    created_at: "2026-06-01T10:00:00Z",
    updated_at: "2026-06-01T10:00:00Z",
  },
  {
    id: "anusree",
    name: "Anusree",
    email: "anusree@hackconnect.dev",
    title: "AI Specialist",
    bio: "AI specialist building intelligent features and data-driven applications.",
    skills: ["Python", "Machine Learning", "Data Science", "NLP"],
    avatar_url: "/team/anusree.jpg",
    hackathons_won: 6,
    hackathons_participated: 12,
    total_projects: 18,
    skill_endorsements: 52,
    years_experience: 6,
    github_contributions: 1580,
    ranking_score: 0,
    rank: 0,
    created_at: "2026-06-01T10:00:00Z",
    updated_at: "2026-06-01T10:00:00Z",
  },
  {
    id: "divakar",
    name: "Divakar",
    email: "divakar@hackconnect.dev",
    title: "Database Lead",
    bio: "Database lead with a focus on reliable data models and queries.",
    skills: ["SQL", "Supabase", "PostgreSQL", "Data Modeling"],
    avatar_url: "/team/divakar.jpg",
    hackathons_won: 4,
    hackathons_participated: 10,
    total_projects: 15,
    skill_endorsements: 38,
    years_experience: 7,
    github_contributions: 2100,
    ranking_score: 0,
    rank: 0,
    created_at: "2026-06-01T10:00:00Z",
    updated_at: "2026-06-01T10:00:00Z",
  },
  {
    id: "hemapriya",
    name: "Hemapriya",
    email: "hemapriya@hackconnect.dev",
    title: "UI/UX Lead",
    bio: "UI/UX designer shaping clear and attractive app experiences.",
    skills: ["UI/UX", "Prototyping", "Design Systems", "User Research"],
    avatar_url: "/team/hemapriya.jpg",
    hackathons_won: 10,
    hackathons_participated: 16,
    total_projects: 22,
    skill_endorsements: 65,
    years_experience: 3,
    github_contributions: 750,
    ranking_score: 0,
    rank: 0,
    created_at: "2026-06-01T10:00:00Z",
    updated_at: "2026-06-01T10:00:00Z",
  },
  {
    id: "bharani",
    name: "Bharani",
    email: "bharani@hackconnect.dev",
    title: "Cloud Lead",
    bio: "Cloud developer focused on deployment, monitoring, and infrastructure.",
    skills: ["Cloud", "Docker", "CI/CD", "DevOps"],
    avatar_url: "/team/bharani.jpg",
    hackathons_won: 3,
    hackathons_participated: 8,
    total_projects: 10,
    skill_endorsements: 28,
    years_experience: 8,
    github_contributions: 420,
    ranking_score: 0,
    rank: 0,
    created_at: "2026-06-01T10:00:00Z",
    updated_at: "2026-06-01T10:00:00Z",
  },
]
